title: OneShot Solstice Replay MOD
description: ゲーム OneShot において通常 1 度しかプレイできない Solstice ルートをリプレイ可能にするファンメイド MOD。
image: oneshot.jpg
links:
  - name: Download
    href: https://steamcommunity.com/sharedfiles/filedetails/?id=1847319248
  - name: GitHub
    href: https://github.com/proudust/oneshot-solstice-replay-mod
