title: MAS 日本語化パッチ (DDLC翻訳部)
description: ゲーム Doki Doki Literature Club! のファンメイド MOD、Monika After Storyを日本語化する非公式パッチ。翻訳所とパッチの作成・配布、一部翻訳を担当。
image: mas.png
links:
  - name: Download
    href: https://steamcommunity.com/sharedfiles/filedetails/?id=1331592265
  - name: GitHub
    href: https://github.com/proudust/ddlc-mas-jp-patch
