env:
  browser: true
  es6: true
  node: true

extends:
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:react/recommended
  - react-app

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json

plugins:
  - "@typescript-eslint"
  - prettier
  - react

rules:
  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowExpressions: true
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: "all"
  react/prop-types:
    - off
