env:
  browser: true
  es6: true
  node: true

extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
  - react-app

plugins:
  - prettier
  - react

rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: "all"
      printWidth: 100
  react/prop-types:
    - off

overrides:
  - files: ["**/*.ts"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaFeatures:
        jsx: true
      ecmaVersion: 2018
      sourceType: module
      project: tsconfig.json

    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
    plugins:
      - "@typescript-eslint"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowExpressions: true
