title: DDLC 日本語化パッチ (DDLC翻訳部)
description: ゲーム Doki Doki Literature Club! (邦題：ドキドキ文芸部) を日本語化する非公式パッチ。翻訳所とパッチの作成・配布を担当。
image: ddlc.png
links:
  - name: Download
    href: https://steamcommunity.com/sharedfiles/filedetails/?id=1296040205
  - name: GitHub
    href: https://github.com/proudust/ddlc-jp-patch
