title: PAYDAY2 Big Oil Day2 Calculator
description: ゲーム PAYDAY2 の Big Oil Day2 で正解の融合炉を探すための計算機。
image: bigoil.png
links:
  - name: Link
    href: https://proudust.github.io/payday2-bigoil/
  - name: GitHub
    href: https://github.com/proudust/payday2-bigoil
