rules:
  # 「ですます」調と「である」調のどちらか多い方に統一する
  # https://github.com/textlint-ja/textlint-rule-no-mix-dearu-desumasu
  no-mix-dearu-desumasu:
    preferInHeader: ""
    preferInBody: ""
    preferInList: ""
    strict: true

  # https://github.com/textlint-ja/textlint-rule-spacing
  preset-ja-spacing:
    # カタカナ語間は中黒または半角スペースを用いてカタカナ語を区切る
    ja-nakaguro-or-halfwidth-space-between-katakana: true

    # かっこの外側、内側ともにスペースを入れないようにする
    ja-no-space-around-parentheses: true

    # 全角文字同士の間にスペースを入れない
    ja-no-space-between-full-width: true

    # 半角文字と全角文字の間にスペースを入れる
    ja-space-between-half-and-full-width:
      space: always

    # 文末に感嘆符を使用し、後に別の文が続く場合は、直後に全角スペースを挿入する
    ja-space-after-exclamation: true

    # 文末に疑問符を使用し、後に別の文が続く場合は、直後に全角スペースを挿入する
    ja-space-after-question: true

    # インラインコードの周りにスペースを入れる
    ja-space-around-code:
      before: true
      after: true
