title: Dweller's Empty Path 日本語化パッチ (制作協力)
description: ゲーム Dweller's Empty Path を日本語化する非公式パッチ。翻訳所とパッチの作成・配布を担当。
image: dwellers-empty-path.png
links:
  - name: Download
    href: https://github.com/proudust/dwellers-empty-path-jp-patch/releases/latest
  - name: GitHub
    href: https://github.com/proudust/dwellers-empty-path-jp-patch
