env:
  browser: true
  es6: true
  node: true

extends:
  - plugin:react/recommended
  - prettier
  - react-app

parserOptions:
  sourceType: module
  ecmaVersion: 2018

plugins:
  - react

rules:
  react/prop-types:
    - off

overrides:
  - files: ['**/*.ts']
    parser: '@typescript-eslint/parser'
    extends:
      - plugin:@typescript-eslint/recommended
    plugins:
      - '@typescript-eslint'

    rules:
      '@typescript-eslint/explicit-function-return-type':
        - warn
        - allowExpressions: true
