title: Escaped Chasm 日本語化パッチ (制作協力)
description: ゲーム Escaped Chasm を日本語化する非公式パッチ。翻訳所とパッチの作成・配布を担当。
image: escaped-chasm.png
links:
  - name: Download
    href: https://github.com/proudust/escaped-chasm-jp-patch/releases/latest
  - name: GitHub
    href: https://github.com/proudust/escaped-chasm-jp-patch
