title: DDLC 3rd-anniv Twitch Writes Mod (DDLC翻訳部)
description: ゲーム Doki Doki Literature Club! の 3 周年記念公式配信で行われた企画、を日本語化するTwitch Writes の内容を再現するファンメイド MOD。翻訳所と MOD の作成・配布を担当。
image: 3rd-anniv-twitch-writes.png
links:
  - name: Download
    href: https://github.com/proudust/ddlc-3rd-anniv-twitch-writes/releases/latest
  - name: GitHub
    href: https://github.com/proudust/ddlc-3rd-anniv-twitch-writes
