name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          cache: yarn

      - name: Use textlint problem matcher
        run: echo "::add-matcher::.github/textlint-matcher.json"

      - name: Restore node modules
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Type Check
        run: yarn workspace front tsc

      - name: Deploy
        if: github.ref == 'refs/heads/master-src'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: ./packages/front/public
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          user_name: github-actions[bot]
