name: ncu

on:
  repository_dispatch:
    types: [ncu]
  schedule:
    - cron: "0 21 * * *"

jobs:
  ncu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Use yarn cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.cache-name }}-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Run npm-check-updates
        run: |
          yarn global add npm-check-updates
          `yarn global bin`/ncu -u --packageFile packages/front/package.json
          `yarn global bin`/ncu -u --packageFile packages/posts/package.json
          yarn

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: ":arrow_up: Update dependencies"
          title: Update dependencies
          body: |
            This pull request is automatically generated by GitHub Actions workflow.
            Dependencies update by [raineorshine/npm-check-updates](https://github.com/raineorshine/npm-check-updates) every morning at 6am (JST).
          labels: automated pr
          assignees: proudust
          reviewers: proudust
          branch: update-deps
